version: "3"

services:
  
  bot:
    image: dockergelb/werewolf-bot
    container_name: werewolf_bot
    env_file: .env

  postgres:
    image: postgres
    container_name: werewolf_db
    env_file: .env
    expose: [5432]
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: